"""add_first_attempted_at_and_lifecycle_timestamps

Revision ID: 15a086ed2990
Revises: f739479ac82f
Create Date: 2026-08-08 13:59:10.300305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a086ed2990'
down_revision: Union[str, Sequence[str], None] = 'f739479ac82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable initially
    op.add_column('user_problems', sa.Column('first_attempted_at', sa.DateTime(), nullable=True))
    
    # 2. Backfill first_attempted_at using created_at for existing records
    op.execute("UPDATE user_problems SET first_attempted_at = created_at WHERE first_attempted_at IS NULL")
    
    # 3. Enforce NOT NULL constraint
    op.alter_column('user_problems', 'first_attempted_at', nullable=False)
    
    # 4. Backfill solved_at using updated_at for existing SOLVED / MASTERED records
    op.execute("UPDATE user_problems SET solved_at = updated_at WHERE status IN ('SOLVED', 'MASTERED') AND solved_at IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_problems', 'first_attempted_at')
    # ### end Alembic commands ###
