"""extend user problem

Revision ID: 7e2ddf0dbbdf
Revises: 04f9b07c25e3
Create Date: 2026-08-01 23:03:17.166453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2ddf0dbbdf'
down_revision: Union[str, Sequence[str], None] = '04f9b07c25e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_problems', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('user_problems', sa.Column('revision_count', sa.Integer(), nullable=False))
    op.add_column('user_problems', sa.Column('favorite', sa.Boolean(), nullable=False))
    op.add_column('user_problems', sa.Column('solution_url', sa.String(length=500), nullable=True))
    op.add_column('user_problems', sa.Column('last_revised_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_user_problem', 'user_problems', ['user_id', 'problem_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_problem', 'user_problems', type_='unique')
    op.drop_column('user_problems', 'last_revised_at')
    op.drop_column('user_problems', 'solution_url')
    op.drop_column('user_problems', 'favorite')
    op.drop_column('user_problems', 'revision_count')
    op.drop_column('user_problems', 'language')
    # ### end Alembic commands ###
