"""update_user_problem_tracker_schema

Revision ID: b04bd0f55516
Revises: 7e2ddf0dbbdf
Create Date: 2026-08-02 12:51:25.683592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04bd0f55516'
down_revision: Union[str, Sequence[str], None] = '7e2ddf0dbbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE problemstatus ADD VALUE IF NOT EXISTS 'ATTEMPTING';")
        op.execute("ALTER TYPE problemstatus ADD VALUE IF NOT EXISTS 'NEEDS_REVISION';")
        op.execute("ALTER TYPE problemstatus ADD VALUE IF NOT EXISTS 'MASTERED';")
    op.add_column('user_problems', sa.Column('time_taken_minutes', sa.Integer(), nullable=True))
    op.add_column('user_problems', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_problems', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('user_problems', 'time_taken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_problems', sa.Column('time_taken', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_problems', 'updated_at')
    op.drop_column('user_problems', 'created_at')
    op.drop_column('user_problems', 'time_taken_minutes')
    # ### end Alembic commands ###
