"""add_topics_and_problem_import_fields

Revision ID: f739479ac82f
Revises: b04bd0f55516
Create Date: 2026-08-03 11:54:56.693267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f739479ac82f'
down_revision: Union[str, Sequence[str], None] = 'b04bd0f55516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('problem_topics',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'topic_id')
    )
    op.add_column('problems', sa.Column('frontend_question_id', sa.String(length=20), nullable=True))
    op.add_column('problems', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('problems', sa.Column('acceptance_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'acceptance_rate')
    op.drop_column('problems', 'is_premium')
    op.drop_column('problems', 'frontend_question_id')
    op.drop_table('problem_topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
